# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Davide"
description:        "publishing + technology + attention"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//davideberretta.com"
author:             "Davide"
twitter:
  username:         "@daveeday"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "Consulting"
    href:           "//kiko.gfjaru.com/about"
  - name:           "Fleisure"
    href:           "//github.com/gfjaru/Kiko/releases"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
